tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: right
  pad_token_as_eos_token: False
  max_length: 20

reward_fn:
  id: meteor
#  id: meteor
#  args:
#    shaping_fn: "common_gen_repeat_penalty"


datapool:
  id: commongen
  frac_train_samples: -1
  train_samples_rnd_seed: -1
  args:
    concept_end_token: '.'
    concept_separator_token: ' '
    prefix: "generate a sentence with: "

env:
  n_envs: 10
  args:
    max_prompt_length: 20
    max_episode_length: 20
    terminate_on_eos: True
    context_start_token: 0
    prompt_truncation_side: "right"

alg:
  id: nlpo
  args:
    n_steps: 128
    batch_size: 64
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5
    enforce_token_entropy_reg_estimate: False
    ent_coef: 0.01
  kl_div:
    coeff: 0.001
    target_kl: 2.0
  policy:
    id: maskable_seq2seq_lm_actor_critic_policy
    args:
      model_name: t5-base
      apply_model_parallel: True
      prompt_truncation_side: "right"
      mask_type: "learned_top_p"
      top_mask: 0.9
      target_update_iterations: 20
      generation_kwargs:
        temperature: 1
        do_sample: True
        top_k: 0
        min_length: 5
        max_new_tokens: 20

train_evaluation:
  eval_batch_size: 20
  n_iters: 100
  eval_every: 20
  save_every: 1
  metrics:
    - id: meteor
      args: { }
    - id: meteor_common_gen_repeat_penalty
    - id: rouge
    - id: bleu
      args: { }
    - id: bert_score
      args:
        language: en
    # - id: bleurt
    #   args:
    #     config_name: bleurt-large-512
    - id: diversity
      args: { }
    # - id: summaCZS
    #   args:
    #     granularity: sentence
    #     use_ent: True
    #     use_con: False
    # - id: summaCConv
    #   args:
    #     granularity: sentence
  generation_kwargs:
    num_beams: 5
    min_length: 5
    max_new_tokens: 20
